// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDo.Entity
{
    [Keyless]
    public partial class ToDoVIew
    {
        public int ID { get; set; }
        [Required]
        [StringLength(20)]
        public string UserName { get; set; }
        [Required]
        [StringLength(20)]
        public string Name { get; set; }
        [StringLength(150)]
        public string Describe { get; set; }
        [StringLength(20)]
        public string Type { get; set; }
        [StringLength(20)]
        public string StartDate { get; set; }
        [StringLength(20)]
        public string EndDate { get; set; }
        [StringLength(10)]
        public string State { get; set; }
        [StringLength(10)]
        public string Priority { get; set; }
    }
}