// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDo.Entity
{
    public partial class Type
    {
        [Key]
        public int ID { get; set; }
        [Column("Type")]
        [StringLength(20)]
        public string type { get; set; }
    }
}